#use_frameworks!
#source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'HTBaseModule_Example' do
  pod 'HTBaseModule', :path => '../'

  target 'HTBaseModule_Tests' do
    inherit! :search_paths    
  end
end
